name: Deploy using cache and outputs file
on: 
  push:
    branches: [main, dev]
  workflow_dispatch: 
env:
  DAY_OF_WEEK: Monday
jobs:
  deploying:
    uses: ./.github/workflows/CacheAndOutputs.yml
    with:
      java-version: 21
    # run: echo "Today is ${{ env.DAY_OF_WEEK }}" Cannot have steps and runs-on if we have uses under a job. 
