name: Deploy using cache and outputs file
on: 
  push:
    branches: [main, dev]
  workflow_dispatch: 
env:
  DAY_OF_WEEK: Monday
jobs:
  deploy:
    uses: ./.github/workflows/CacheAndOutputs.yml
    with:
      java-version: 21
