name: Deploy using cache and outputs file
on: 
  push:
    branches: [main, dev]
  workflow_dispatch: 
jobs:
  deploy:
    uses: ./.github/workflows/CacheAndOutputs.yml
    with:
      java-version: 21
