name: Matrix Strategy
on: workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        java-versions: [11, 17, 21]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - java-versions: 25
            operating-system: ubuntu-latest
        exclude:
          - java-versions: 11
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-versions }}
          distribution: 'temurin'
      - name: Execute permissions to maven
        run: chmod +x mvnw
      - name: Maven Build
        run: ./mvnw clean package
