name: Matrix Strategy
on: workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        java_versions: [11, 17, 21]
        operating_system: [ubuntu-latest, windows-latest]
        include:
          - java_versions: 25
            operating_system: ubuntu-latest
        exclude:
          - java_versions: 11
            operating_system: windows-latest
    runs-on: ${{ matrix.operating_system }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_versions }}
          distribution: 'temurin'
          
      - name: Execute permissions to maven (Linux/Ubuntu)
        if: runner.os != 'Windows'
        run: chmod +x mvnw
        
      - name: Maven Build (Linux/Ubuntu)
        if: runner.os != 'Windows'
        run: ./mvnw clean package

      - name: Maven Build (Windows)
        if: runner.os == 'Windows'
        run: mvnw.cmd clean package
