name: Time to Practice
on: workflow_dispatch
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven
      - name: Verify Java Installation
        run: java -version
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v4
        with: 
          java-version: '21'
          distribution: temurin
          cache: maven
      - name: Give execute permissions to Maven wrapper
        run: chmod +x mvnw
      - name: Build the Application
        run: ./mvnw clean package  
