name: Setup Environment
on:
  # push:
  #   branches:
  #     - main
  #     - 'dev/*'
  #     - 'feature/**'
  #   paths-ignore:
  #     - '.github/workflows'
  workflow_dispatch:
  pull_request:
    types:
      - reopened
      - opened
jobs:
  #Job 1 - Checout the repository and setup JDK and then build the repository using maven
  build:
    runs-on: ubuntu-latest
    steps:
      #Step 1 - Checkout repository
      - name: Checkout code
        uses: actions/checkout@v7
      #Step 2 - Setup JDK
      - name: Install dependencies/Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
       #Step 3 - Build the code
      - name: Build the code using Maven/First given execute access to maven
        run: chmod +x mvnw
      - name: Now build the code using maven
        run: ./mvnw clean package
